import { DEMO_USERS, type Country, type SourceKind, type SourceStatus } from '@tectonic/shared';
import { count, sql } from 'drizzle-orm';
import type { Database } from './client.ts';
import { projectMembers, projects, sources, users } from './schema.ts';

interface SeedTeam {
  key: string;
  name: string;
  description: string;
  color: string;
  ownerId: string;
  members: Array<{ userId: string; role: 'editor' | 'viewer' }>;
}

interface SeedSource {
  code: string;
  team: string;
  title: string;
  kind: SourceKind;
  version?: number;
  topic: string;
  keywords: string;
  country: Country;
  client?: string;
  value: string;
  claim: string;
  quote: string;
  validFrom: string;
  validTo?: string;
  status: SourceStatus;
  ownerId?: string;
  approvedById?: string;
  traceable?: boolean;
  supersededBy?: string;
  /** Extra teams (keys) the viewer must also belong to. */
  audience?: string[];
}

/**
 * Wanne, Roy and Sebastien are the three payroll consultants of the demo. Wanne asks the questions.
 * Sebastien is NOT in "Klantteam Atlas", so he cannot see the Atlas agreement: access is part of trust.
 */
const TEAMS: SeedTeam[] = [
  {
    key: 'be',
    name: 'Payroll België',
    description: 'Procedures en handleidingen voor payroll in België en Nederland.',
    color: '#4f46e5',
    ownerId: 'demo_roy',
    members: [
      { userId: 'demo_wanne', role: 'editor' },
      { userId: 'demo_sebastien', role: 'editor' },
    ],
  },
  {
    key: 'atlas',
    name: 'Klantteam Atlas',
    description: 'Afspraken en gesprekken met klant Atlas.',
    color: '#0ea5e9',
    ownerId: 'demo_roy',
    members: [{ userId: 'demo_wanne', role: 'editor' }],
  },
];

const LOONMUTATIES = 'loonmutaties aanleveren aanleverdatum deadline inleveren doorgeven';
const ZIEKMELDING = 'ziekmelding ziek melden afwezigheid termijn doorgeven';

// Fixed case dates keep October/November reproducible; DB createdAt/updatedAt use insertion time.
// Dossier adaptations and source-code mapping: docs/scenarios.md. All additional rules are fictional.
const SOURCES: SeedSource[] = [
  {
    code: 'S4',
    team: 'atlas',
    title: 'Klantafspraak Atlas',
    kind: 'agreement',
    version: 2,
    topic: 'loonmutaties',
    keywords: LOONMUTATIES,
    country: 'BE',
    client: 'Atlas',
    value: '22 oktober 2026',
    claim: 'Voor Atlas geldt een goedgekeurde uitzondering op de algemene aanleverdatum van 20 oktober.',
    quote: 'Atlas mag loonmutaties aanleveren tot en met 22 oktober 2026.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_roy',
    approvedById: 'demo_roy',
  },
  {
    code: 'S1',
    team: 'be',
    title: 'Algemene procedure België',
    kind: 'manual',
    version: 5,
    topic: 'loonmutaties',
    keywords: LOONMUTATIES,
    country: 'BE',
    value: '20 oktober',
    claim: 'Loonmutaties worden uiterlijk op 20 oktober van de maand aangeleverd.',
    quote: 'Loonmutaties moeten uiterlijk op de 20e van de maand binnen zijn.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S2',
    team: 'be',
    title: 'Oude procedure België',
    kind: 'procedure',
    version: 3,
    topic: 'loonmutaties',
    keywords: LOONMUTATIES,
    country: 'BE',
    value: '15 oktober',
    claim: 'Loonmutaties worden uiterlijk op 15 van de maand aangeleverd.',
    quote: 'Aanleveren kan tot de 15e van de maand.',
    validFrom: '2024-01-01',
    validTo: '2025-12-31',
    status: 'superseded',
    approvedById: 'demo_sebastien',
    supersededBy: 'S1',
  },
  {
    code: 'S3',
    team: 'atlas',
    title: 'Teamsgesprek',
    kind: 'chat',
    topic: 'loonmutaties',
    keywords: LOONMUTATIES,
    country: 'BE',
    client: 'Atlas',
    value: '25 oktober',
    claim: 'Volgens een bericht in het team mag Atlas tot 25 oktober aanleveren.',
    quote: 'Ik dacht dat Atlas dit keer tot de 25e mocht aanleveren?',
    validFrom: '2026-10-05',
    status: 'unconfirmed',
  },
  {
    code: 'S5',
    team: 'be',
    title: 'Procedure Nederland',
    kind: 'procedure',
    version: 2,
    topic: 'loonmutaties',
    keywords: LOONMUTATIES,
    country: 'NL',
    value: '18 oktober',
    claim: 'In Nederland worden loonmutaties uiterlijk op 18 oktober aangeleverd.',
    quote: 'Nederlandse klanten leveren loonmutaties aan tot de 18e.',
    validFrom: '2026-01-01',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S6',
    team: 'be',
    title: 'Procedure ziekmelding België',
    kind: 'procedure',
    version: 4,
    topic: 'ziekmelding',
    keywords: ZIEKMELDING,
    country: 'BE',
    value: 'Binnen 24 uur',
    claim: 'Een ziekmelding wordt binnen 24 uur doorgegeven aan payroll.',
    quote: 'Ziekmeldingen worden binnen 24 uur na de eerste ziektedag doorgegeven.',
    validFrom: '2026-01-01',
    status: 'approved',
    ownerId: 'demo_roy',
    approvedById: 'demo_roy',
  },
  {
    // An older version nobody marked as replaced yet: try "Markeer als vervangen door S6" in the source panel.
    code: 'S34',
    team: 'be',
    title: 'Procedure ziekmelding België (oud)',
    kind: 'procedure',
    version: 3,
    topic: 'ziekmelding',
    keywords: ZIEKMELDING,
    country: 'BE',
    value: 'Binnen 72 uur',
    claim: 'Een ziekmelding wordt binnen 72 uur doorgegeven aan payroll.',
    quote: 'Ziekmeldingen worden binnen 72 uur na de eerste ziektedag doorgegeven.',
    validFrom: '2023-01-01',
    validTo: '2025-12-31',
    status: 'approved',
    ownerId: 'demo_roy',
    approvedById: 'demo_roy',
  },
  {
    code: 'S7',
    team: 'atlas',
    title: 'Teamsgesprek ziekmelding',
    kind: 'chat',
    topic: 'ziekmelding',
    keywords: ZIEKMELDING,
    country: 'BE',
    client: 'Atlas',
    value: 'Binnen 48 uur',
    claim: 'Volgens een bericht mag Atlas ziekmeldingen binnen 48 uur doorgeven.',
    quote: 'Atlas zei dat 48 uur ook goed is voor ziekmeldingen.',
    validFrom: '2026-09-01',
    status: 'unconfirmed',
  },
  {
    // Restricted: lives in Payroll België but only people in BOTH Payroll België and Klantteam Atlas may see it.
    // Sebastien (only Payroll België) does not see it anywhere.
    code: 'S8',
    team: 'be',
    audience: ['atlas'],
    title: 'Afspraak Atlas: eindejaarspremie',
    kind: 'agreement',
    version: 1,
    topic: 'eindejaarspremie',
    keywords: 'eindejaarspremie premie uitbetalen uitbetaling december Atlas',
    country: 'BE',
    client: 'Atlas',
    value: '15 december',
    claim: 'Voor Atlas wordt de eindejaarspremie uiterlijk op 15 december uitbetaald.',
    quote: 'Atlas en SD Worx spreken af dat de eindejaarspremie uiterlijk op 15 december wordt uitbetaald.',
    validFrom: '2026-01-01',
    status: 'approved',
    ownerId: 'demo_roy',
    approvedById: 'demo_roy',
  },
  {
    code: 'S9',
    team: 'atlas',
    title: 'Mailketen Atlas: verzoek en vastlegging',
    kind: 'chat',
    topic: 'loonmutaties',
    keywords: 'loonmutaties aanleveren aanleverdatum',
    country: 'BE',
    value: 'Verzoek vastgelegd in S4',
    claim: 'De mailketen verwijst voor de definitieve oktoberafspraak naar S4.',
    quote: 'Bewerking van dossier S3, mailwisseling van 25 tot 28 september. 25 september, Lotte aan Roy: onze tweede interne controle vraagt extra tijd; kunnen we de volledige reguliere loonmutaties op 22 oktober bezorgen? Roy: ik vraag capaciteit en bevoegd akkoord na, tot dan blijft de algemene planning staan. 26 september, planning aan Roy: de capaciteit is onderzocht, dit is nog geen goedkeuring. 28 september, Roy aan Lotte en Wanne: de vastgestelde afspraak is geregistreerd als S4. Lotte bevestigt ontvangst en vraagt afzonderlijke planning voor november. De mail verwijst naar de afspraak, zij wijzigt die niet.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'unconfirmed',
    ownerId: 'demo_roy',
    client: 'Atlas',
  },
  {
    code: 'S10',
    team: 'atlas',
    title: 'Atlasoverleg: opties en open acties',
    kind: 'chat',
    topic: 'loonmutaties',
    keywords: 'loonmutaties aanleveren planning overleg',
    country: 'BE',
    value: '23 oktober was een voorstel',
    claim: 'Tijdens het overleg is 23 oktober verkend zonder een wijziging goed te keuren.',
    quote: 'Bewerking van dossier S5 en de context bij bordfoto S9, overleg 25 september. Aanwezig: Lotte, Roy, Wanne en planning. Lotte licht het nieuwe controlescherm toe; het exportformaat blijft gelijk. Planning noemt 23 oktober als mogelijke extra dag en zet een vraagteken op het bord. Actie Roy: capaciteit en goedkeuring onderzoeken. Er is geen besluit over uitstel genomen. De volledige foto blijft bij de notulen zodat het open actiepunt zichtbaar is. De latere vastgestelde afspraak staat afzonderlijk in S4.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'unconfirmed',
    ownerId: 'demo_roy',
    client: 'Atlas',
  },
  {
    code: 'S11',
    team: 'atlas',
    title: 'Teams Atlas: herinnering en correctie',
    kind: 'chat',
    topic: 'loonmutaties',
    keywords: 'loonmutaties aanleveren teams afspraak',
    country: 'BE',
    value: 'Raadpleeg de vastgestelde afspraak',
    claim: 'Een herinnering aan het overleg is geen nieuwe klantafspraak.',
    quote: 'Bewerking van dossier S6, Teams op 29 september. 09.02 Wanne: welke Belgische procedure gebruiken we bij de overdracht? 09.05 Roy: S1; de oude versie blijft als historiek staan. 09.08 Planning: ik herinner me de 23ste van het bord. 09.11 Wanne: daar staat ook een vraagteken, is dat ooit beslist? 09.14 Planning: nee, het was een optie voor capaciteitsonderzoek. 09.18 Roy: de beslissing staat in S4, open die bij een klantantwoord. 09.45 Lotte: geldt dit ook voor november? 09.48 Roy: daarvoor is nog geen goedgekeurd stuk beschikbaar. Wanne neemt de novembervraag op in de opvolging.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'unconfirmed',
    ownerId: 'demo_roy',
    client: 'Atlas',
  },
  {
    code: 'S12',
    team: 'be',
    title: 'Werkafspraak: vastleggen van een klantuitzondering',
    kind: 'manual',
    version: 1,
    topic: 'dossierbeheer',
    keywords: 'dossierbeheer bevoegdheid goedkeuring vastleggen',
    country: 'BE',
    value: 'Bewaar besluit, versie en klantaanvaarding',
    claim: 'Een afwijking wordt pas vastgelegd na een expliciet besluit voor de juiste klant en periode.',
    quote: 'Bewerking van dossier S0. Wanne bereidt klantantwoorden voor en controleert land, periode en soort verwerking. Roy beoordeelt verzoeken om van de algemene werkwijze af te wijken. Bewaar het goedgekeurde document met versie, besluit en klantaanvaarding. Een haalbaarheidsadvies van planning geldt niet als besluit. Wijzig historische notulen niet achteraf. Een kopie van dezelfde afspraak is geen extra onafhankelijke bevestiging.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_roy',
    approvedById: 'demo_roy',
  },
  {
    code: 'S13',
    team: 'atlas',
    title: 'Portefeuilleoverdracht Atlas: stand vóór klantoverleg',
    kind: 'manual',
    version: 1,
    topic: 'portefeuilleoverdracht',
    keywords: 'portefeuille overdracht dossierstand',
    country: 'BE',
    value: 'Dossierstand op 25 september om 09.00 uur',
    claim: 'De overdracht beschrijft de algemene regeling vóór het latere klantverzoek.',
    quote: 'Bewerking van dossier S10. Roy draagt op 25 september om 09.00 uur het Belgische Atlasdossier over aan Wanne. Het register bevat op dat moment alleen de algemene procedure en de gearchiveerde voorganger; er is geen vastgestelde klantuitzondering geregistreerd. De Nederlandse procedure is beschikbaar als referentie voor het andere land. Het overleg met Atlas vindt later die dag plaats. Deze momentopname is geen verklaring over de volledigheid van het dossier na dat overleg. Wanne moet nieuwe besluiten na de overdracht afzonderlijk controleren.',
    validFrom: '2026-09-25',
    validTo: '2026-09-25',
    status: 'approved',
    ownerId: 'demo_roy',
    approvedById: 'demo_roy',
    client: 'Atlas',
  },
  {
    code: 'S14',
    team: 'be',
    title: 'Werkproces verlofregistratie België',
    kind: 'procedure',
    version: 1,
    topic: 'verlof',
    keywords: 'verlof vakantie aanvragen saldo',
    country: 'BE',
    value: 'Leidinggevende bevestigt vóór verwerking',
    claim: 'Verlof wordt verwerkt nadat de leidinggevende de aanvraag en het saldo heeft bevestigd.',
    quote: 'Fictieve interne procesafspraak, vrijgegeven door Sebastien op 30 september. De medewerker registreert de dagen in het verlofportaal. De leidinggevende controleert bezetting en saldo en bevestigt de aanvraag; payroll verwerkt daarna de juiste afwezigheidscode. Een mondeling akkoord of kalenderblok alleen volstaat niet als verwerkingsopdracht. Bij een verschil tussen portaal en planning vraagt payroll herstel aan de leidinggevende en bewaart de bestaande registratie tot het antwoord er is. Deze werkwijze bepaalt geen wettelijk verlofrecht.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S15',
    team: 'be',
    title: 'Teams: verlof via een kalenderblok',
    kind: 'chat',
    topic: 'verlof',
    keywords: 'verlof vakantie aanvragen kalender',
    country: 'BE',
    value: 'Kalenderblok zou voldoende zijn',
    claim: 'Een collega vermoedt dat een kalenderblok de formele verlofaanvraag vervangt.',
    quote: 'Teams Payroll, 2 oktober. 10.12 Wanne: in de agenda staan drie vakantiedagen, maar ik zie geen portaalbevestiging. 10.15 Collega: vorig jaar namen we het kalenderblok gewoon over, dat zal nog wel mogen. 10.19 Sebastien: ik heb geen wijziging van S14 ontvangen; vraag de leidinggevende om de aanvraag in het portaal te bevestigen. 10.23 Wanne: ik laat het dossier open tot de registratie klopt. Het gesprek bevat geen besluit om de procedure te wijzigen.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'unconfirmed',
  },
  {
    code: 'S16',
    team: 'be',
    title: 'Controlelijst loonindexering België',
    kind: 'manual',
    version: 1,
    topic: 'loonindexering',
    keywords: 'loonindexering index indexatie barema',
    country: 'BE',
    value: 'Controleer toepasselijk barema en ingangsdatum',
    claim: 'Payroll past een indexering pas toe na controle van het toepasselijke barema en de ingangsdatum.',
    quote: 'Fictieve controlelijst, versie 1. Het klantdossier moet de toepasselijke regeling en de gevalideerde barematabel bevatten. Vergelijk de nieuwe tabel met de bestaande looncomponenten en registreer vanaf welke loonperiode zij geldt. Laat een tweede consultant de berekening en selectie controleren. Een percentage uit een nieuwsbrief wordt niet zonder die controles voor alle medewerkers gebruikt. Ontbreekt de gevalideerde tabel, vraag die op bij de dossierverantwoordelijke; deze bron bevat zelf geen indexpercentage.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S17',
    team: 'be',
    title: 'Losse notitie: indexpercentage zonder herkomst',
    kind: 'chat',
    topic: 'loonindexering',
    keywords: 'loonindexering index percentage',
    country: 'BE',
    value: '2 procent, onbevestigd',
    claim: 'Een losse notitie noemt 2 procent zonder regeling, eigenaar of herleidbare tabel.',
    quote: 'In de overdrachtsmap staat: "Index volgende verwerking ongeveer 2 procent? Nog controleren." De notitie heeft geen auteur, bijlage of verwijzing naar een barema. Het is niet duidelijk voor welke sector, medewerkers of ingangsdatum de schrijver dit bedoelde. De ontvanger heeft alleen deze tekst overgenomen en kon het originele bestand niet terugvinden. Er is geen geregistreerd akkoord om dit percentage te verwerken.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'unconfirmed',
    traceable: false,
  },
  {
    code: 'S18',
    team: 'be',
    title: 'Werkproces overuren België',
    kind: 'procedure',
    version: 1,
    topic: 'overuren',
    keywords: 'overuren extra uren toeslag tijdregistratie',
    country: 'BE',
    value: 'Goedgekeurde urenstaat en toepasselijke regeling',
    claim: 'Voor overuren zijn een goedgekeurde urenstaat en controle van de toepasselijke regeling nodig.',
    quote: 'Fictieve verwerkingsprocedure. De teamverantwoordelijke bevestigt per medewerker de datum en het aantal extra uren in de urenstaat. Payroll controleert de toepasselijke looncode en regeling voordat een toeslag of compensatie wordt verwerkt. Een totaal in een chat zonder dagen en goedkeuring is geen volledige invoer. Bij correcties blijft de eerdere urenstaat bewaard en wordt de gewijzigde versie herkenbaar geregistreerd. De procedure legt geen algemeen toeslagpercentage vast.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S19',
    team: 'atlas',
    title: 'Atlas: aanlevering urenstaat via teamleider',
    kind: 'agreement',
    version: 1,
    topic: 'overuren',
    keywords: 'overuren urenstaat teamleider',
    country: 'BE',
    value: 'Teamleider bundelt en bevestigt de urenstaat',
    claim: 'Atlas levert één door de teamleider bevestigde urenstaat aan payroll.',
    quote: 'Fictieve klantwerkafspraak, Roy en Atlas bevestigen versie 1 voor oktober. Medewerkers registreren extra uren met datum en reden. De teamleider controleert de registraties en levert één geconsolideerde urenstaat aan. Payroll controleert vervolgens de looncode volgens S18; dit akkoord verandert geen recht op vergoeding. Bij een ontbrekende medewerker stuurt de teamleider een herkenbare correctieversie, geen tweede losse lijst naast de eerste.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_roy',
    approvedById: 'demo_roy',
    client: 'Atlas',
  },
  {
    code: 'S20',
    team: 'be',
    title: 'Overurenprocedure Nederland',
    kind: 'procedure',
    version: 1,
    topic: 'overuren',
    keywords: 'overuren urenstaat nederland compensatie',
    country: 'NL',
    value: 'Controleer Nederlandse contractafspraken',
    claim: 'Nederlandse overuren worden verwerkt volgens de gevalideerde contractafspraken in het dossier.',
    quote: 'Fictieve Nederlandse verwerkingsprocedure. Controleer eerst de arbeidsovereenkomst en de geregistreerde toepasselijke regeling. De leidinggevende bevestigt de uren; payroll legt vast of de goedgekeurde verwerking tijd of geld betreft. Een Belgische looncode mag niet automatisch worden gekopieerd naar het Nederlandse dossier. Als het dossier geen gevalideerde regeling bevat, vraagt de consultant aanvulling. Deze bron bepaalt geen algemeen Nederlands toeslagpercentage.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S21',
    team: 'be',
    title: 'Vakantiegeld: controle vóór berekening',
    kind: 'manual',
    version: 1,
    topic: 'vakantiegeld',
    keywords: 'vakantiegeld vakantieattest berekening',
    country: 'BE',
    value: 'Controleer statuut, periode en eerdere betalingen',
    claim: 'Voor de berekening van vakantiegeld controleert payroll de dossiergegevens en eerdere betalingen.',
    quote: 'Fictieve interne controlelijst. Verzamel statuut, relevante tewerkstellingsperiode en beschikbare attesten. Vergelijk eerder verwerkte bedragen met de gevalideerde berekeningsgegevens voordat een nieuwe berekening wordt vrijgegeven. Een bedrag uit het vorige jaar is een controlegegeven en geen nieuw recht. Ontbrekende attesten worden bij de dossierverantwoordelijke opgevraagd. Leg de gebruikte versie en tweede controle vast. De lijst schrijft geen bedrag of percentage voor.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S22',
    team: 'be',
    title: 'Gearchiveerde vakantiegeldchecklist',
    kind: 'procedure',
    version: 1,
    topic: 'vakantiegeld',
    keywords: 'vakantiegeld checklist vorig jaar',
    country: 'BE',
    value: 'Gebruik het vorige jaar als startbedrag',
    claim: 'De oude checklist gebruikte het vorige jaar als startbedrag voor de controle.',
    quote: 'Fictieve checklist uit 2025, archiefregistratie 30 september 2026. De eerdere werkwijze begon met het bedrag van het voorgaande jaar en verzamelde attesten pas bij een verschil. Bij de evaluatie bleek dat dossierwijzigingen zo te laat zichtbaar werden. Sebastien heeft deze checklist daarom vervangen door S21, waarin eerst de actuele basisgegevens worden verzameld. Bewaar dit document alleen om oude berekeningen te reconstrueren.',
    validFrom: '2025-01-01',
    validTo: '2026-09-30',
    status: 'superseded',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
    supersededBy: 'S21',
  },
  {
    code: 'S23',
    team: 'be',
    title: 'Maaltijdcheques: aansluiting op prestaties',
    kind: 'procedure',
    version: 1,
    topic: 'maaltijdcheques',
    keywords: 'maaltijdcheques cheques prestaties telling',
    country: 'BE',
    value: 'Controleer prestaties tegen de klantregeling',
    claim: 'De telling voor maaltijdcheques wordt afgestemd op bevestigde prestaties en de klantregeling.',
    quote: 'Fictieve verwerkingsinstructie. Gebruik de door de klant bevestigde prestaties en controleer de geregistreerde regeling voor maaltijdcheques. Vergelijk uitzonderingsdagen met de overeengekomen codering. Laat verschillen tussen de telling en de prestatiestaat oplossen voordat de bestelling wordt vrijgegeven. De verantwoordelijke bewaart het akkoord op de definitieve telling. Deze algemene procesbron geeft geen bedrag en verleent geen recht voor een individuele werknemer.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S24',
    team: 'be',
    title: 'Teams: maaltijdcheques op alle kalenderdagen',
    kind: 'chat',
    topic: 'maaltijdcheques',
    keywords: 'maaltijdcheques kalenderdagen telling',
    country: 'BE',
    value: 'Alle kalenderdagen, niet bevestigd',
    claim: 'Een Teamsbericht stelt voor alle kalenderdagen te tellen zonder de klantregeling te controleren.',
    quote: 'Teams Payroll, 3 oktober. 14.01 Collega: kunnen we voor de maaltijdcheques gewoon alle kalenderdagen tellen? 14.06 Wanne: dan tellen ook dagen zonder bevestigde prestaties mee, welke regeling bedoel je? 14.11 Collega: ik heb alleen een oude spreadsheet, geen akkoord. 14.17 Sebastien: controleer de prestaties en regeling volgens S23 voordat je bestelt. 14.20 Wanne: bestelling staat nog niet vrijgegeven.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'unconfirmed',
  },
  {
    code: 'S25',
    team: 'be',
    title: 'Nederland: dossiercontrole bij ziekteloon',
    kind: 'procedure',
    version: 1,
    topic: 'ziekteloon',
    keywords: 'ziekteloon loondoorbetaling ziekte nederland',
    country: 'NL',
    value: 'Verifieer contract, ziekteduur en gevalideerde regeling',
    claim: 'Ziekteloon vraagt controle van de toepasselijke regeling en de geregistreerde ziekteperiode.',
    quote: 'Fictieve Nederlandse controleprocedure. De consultant controleert de geregistreerde eerste ziektedag, contractgegevens en de gevalideerde regeling in het klantdossier. Eerdere betalingen worden vergeleken met de bedoelde periode. Een generiek percentage uit een gesprek is geen basis om de looncomponent te wijzigen. Bij ontbrekende contractinformatie vraagt payroll aanvulling bij de verantwoordelijke. Deze bron beschrijft het proces en bevat geen zelfstandig uitbetalingspercentage.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S26',
    team: 'be',
    title: 'Teams Nederland: ziekteloon zonder contractgegevens',
    kind: 'chat',
    topic: 'ziekteloon',
    keywords: 'ziekteloon percentage ziekte',
    country: 'NL',
    value: '100 procent, onbevestigd',
    claim: 'Een collega noemt volledige betaling zonder de contractregeling te hebben gezien.',
    quote: 'Teams Nederland, 6 oktober. 08.50 Collega: volgens mij betalen we altijd 100 procent bij ziekte. 08.54 Wanne: over welke periode en welke contractregeling gaat dit? 09.00 Collega: die gegevens heb ik nog niet, ik ging uit van mijn vorige dossier. 09.08 Sebastien: neem dat percentage niet over; verzamel eerst de gegevens voor S25. Er wordt geen bedrag vrijgegeven in dit gesprek.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'unconfirmed',
  },
  {
    code: 'S27',
    team: 'be',
    title: 'Onkosten: bewijs en zakelijke reden',
    kind: 'manual',
    version: 1,
    topic: 'onkosten',
    keywords: 'onkosten bonnetjes declaratie kosten',
    country: 'BE',
    value: 'Bewijsstuk en zakelijke reden vóór goedkeuring',
    claim: 'Een onkostendeclaratie bevat het bewijsstuk en de zakelijke reden vóór goedkeuring.',
    quote: 'Fictieve werkafspraak. De medewerker voegt het leesbare bewijsstuk, de datum en de zakelijke reden toe aan de declaratie. De leidinggevende controleert de gegevens en voorkomt een dubbele indiening. Payroll verwerkt pas de goedgekeurde registratie met de juiste dossiercode. Een ontbrekend bewijsstuk gaat terug naar de indiener met een concrete vraag. Deze procedure bepaalt geen fiscale vrijstelling.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S28',
    team: 'be',
    title: 'Telewerkvergoeding: losse overdrachtsnotitie',
    kind: 'chat',
    topic: 'telewerkvergoeding',
    keywords: 'telewerk thuiswerk vergoeding bedrag',
    country: 'BE',
    value: 'Bedrag nog te bevestigen',
    claim: 'Voor de telewerkvergoeding ontbreekt een bevestigde klantregeling.',
    quote: 'Losse notitie in de overdrachtsmap, auteur onbekend. "Nieuwe collega vroeg of het thuiswerkbedrag hetzelfde is als bij de vorige werkgever. Nog geen regeling ontvangen; bedrag niet invullen." Er is geen bijlage met een ondertekende afspraak en de dossierverantwoordelijke is niet vermeld. De tekst is als gevonden notitie bewaard, niet als verwerkingsinstructie. De ontbrekende regeling moet eerst worden opgevraagd.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'unconfirmed',
    traceable: false,
  },
  {
    code: 'S29',
    team: 'be',
    title: 'Indiensttreding: controle van de aangifte',
    kind: 'manual',
    version: 1,
    topic: 'indiensttreding',
    keywords: 'indiensttreding dimona start nieuwe medewerker',
    country: 'BE',
    value: 'Controleer startgegevens en aangiftebevestiging',
    claim: 'Bij indiensttreding controleert de consultant de startgegevens en de aangiftebevestiging.',
    quote: 'Fictieve werkchecklist voor het Belgische dossier. Verzamel de door de klant bevestigde startgegevens en controleer de beschikbare aangiftebevestiging. Een interne payrollaanleverdatum vervangt geen aangifteverplichting. Bij een ontbrekend bewijs gaat de vraag naar de verantwoordelijke voor de aangifte. Deze checklist noemt bewust geen wettelijke termijn. Achtergrond over het onderscheid tussen Dimona en DmfA staat in dossier P1 en P3; de checklist is een eigen casusbron, geen kopie van die overheidsteksten.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S30',
    team: 'be',
    title: 'Bankrekeningwijziging: onafhankelijke controle',
    kind: 'procedure',
    version: 1,
    topic: 'bankrekening',
    keywords: 'bankrekening iban rekeningnummer wijzigen',
    country: 'BE',
    value: 'Verifieer via het bestaande contactkanaal',
    claim: 'Een gewijzigd rekeningnummer wordt onafhankelijk geverifieerd voordat payroll het verwerkt.',
    quote: 'Fictieve interne controleprocedure. Registreer het wijzigingsverzoek en controleer de identiteit via het reeds bekende contactkanaal. Gebruik daarvoor niet uitsluitend een nieuw telefoonnummer uit hetzelfde verzoek. Een tweede bevoegde medewerker bevestigt de wijziging en de controle wordt in het dossier vastgelegd. Bij twijfel blijft de bestaande registratie staan en wordt het verzoek onderzocht. Deze casus bevat geen echte bankrekeningnummers.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S31',
    team: 'be',
    title: 'Uitdiensttreding: eindafrekening verzamelen',
    kind: 'manual',
    version: 1,
    topic: 'uitdiensttreding',
    keywords: 'uitdiensttreding eindafrekening vertrek',
    country: 'BE',
    value: 'Verzamel einddatum, saldi en open componenten',
    claim: 'Voor een eindafrekening verzamelt payroll de bevestigde einddatum en open looncomponenten.',
    quote: 'Fictieve checklist. De klant bevestigt de einddatum en levert de nog te verwerken prestaties en saldi aan. Payroll vergelijkt die met reeds verwerkte looncomponenten en controleert welke attestgegevens ontbreken. De verantwoordelijke beoordeelt afwijkingen voordat de afrekening wordt vrijgegeven. Een bedrag uit een eerdere eindafrekening wordt niet gekopieerd. Deze checklist doet geen uitspraak over een individuele ontslagvergoeding.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_sebastien',
    approvedById: 'demo_sebastien',
  },
  {
    code: 'S32',
    team: 'be',
    title: 'Ziekmelding Nederland: interne ontvangstregistratie',
    kind: 'procedure',
    version: 1,
    topic: 'ziekmelding',
    keywords: 'ziekmelding ziek melden afwezigheid termijn doorgeven',
    country: 'NL',
    value: 'Registreer ontvangst op dezelfde werkdag',
    claim: 'De Nederlandse interne werkafspraak registreert een ontvangen ziekmelding op dezelfde werkdag.',
    quote: 'Fictieve Nederlandse werkafspraak. De consultant registreert op dezelfde werkdag wanneer de klantmelding is ontvangen en welke ziekteperiode de klant heeft opgegeven. Onvolledige gegevens worden teruggevraagd aan het bekende contact. Deze ontvangstregistratie is geen Belgische meldtermijn en mag de Belgische procedure S6 niet vervangen. De bron bevat geen medische details en schrijft niet voor welke medische informatie een werkgever mag vragen.',
    validFrom: '2026-10-01',
    validTo: '2026-10-31',
    status: 'approved',
    ownerId: 'demo_roy',
    approvedById: 'demo_roy',
  },
];

export interface SeedResult {
  seeded: boolean;
  users: number;
  projects: number;
  sources: number;
}

/**
 * Inserts the demo users, two teams and the sources. Demo users are always upserted; teams and
 * sources only when the database has no teams yet (or when `reset` wipes them first).
 */
export async function seedDatabase(db: Database, options: { reset?: boolean } = {}): Promise<SeedResult> {
  await db
    .insert(users)
    .values(DEMO_USERS.map((u) => ({ id: u.id, name: u.name, email: u.email, color: u.color })))
    .onConflictDoUpdate({
      target: users.id,
      set: { name: sql`excluded.name`, email: sql`excluded.email`, color: sql`excluded.color` },
    });

  if (options.reset) {
    await db.delete(sources);
    await db.delete(projectMembers);
    await db.delete(projects);
  }

  const [existing] = await db.select({ n: count() }).from(projects);
  if ((existing?.n ?? 0) > 0) return { seeded: false, users: DEMO_USERS.length, projects: 0, sources: 0 };

  const teamIds = new Map<string, string>();
  for (const team of TEAMS) {
    const [row] = await db.insert(projects).values({ name: team.name, description: team.description, color: team.color, ownerId: team.ownerId }).returning();
    if (!row) throw new Error('Failed to insert seed team');
    teamIds.set(team.key, row.id);
    await db.insert(projectMembers).values([
      { projectId: row.id, userId: team.ownerId, role: 'owner' },
      ...team.members.map((m) => ({ projectId: row.id, userId: m.userId, role: m.role })),
    ]);
  }

  await db.insert(sources).values(
    SOURCES.map(({ team, ...s }) => ({
      ...s,
      projectId: teamIds.get(team)!,
      audienceProjectIds: (s.audience ?? []).map((k) => teamIds.get(k)!),
      audience: undefined,
      client: s.client ?? null,
      validTo: s.validTo ?? null,
      version: s.version ?? null,
      ownerId: s.ownerId ?? null,
      approvedById: s.approvedById ?? null,
      supersededBy: s.supersededBy ?? null,
      traceable: s.traceable ?? true,
    })),
  );

  return { seeded: true, users: DEMO_USERS.length, projects: TEAMS.length, sources: SOURCES.length };
}
